version: '3.9'

services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pass
        ports:
        - "27017:27017"
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: delivery
        ports:
            - "5432:5432"
   