"""empty message

Revision ID: 25effa7418ba
Revises: 303f574556ab
Create Date: 2024-09-07 01:35:21.084226

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25effa7418ba"
down_revision = "303f574556ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consumer",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consumer", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_consumer_document"), ["document"], unique=True
        )

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )

    with op.batch_alter_table("consumer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consumer_document"))

    op.drop_table("consumer")
    # ### end Alembic commands ###
