"""empty message

Revision ID: 36d1c2986a5a
Revises: 8d0a06f605ca
Create Date: 2024-09-23 18:24:18.731369

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36d1c2986a5a"
down_revision = "8d0a06f605ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("consumer", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_name", sa.String(), nullable=True))

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )

    with op.batch_alter_table("consumer", schema=None) as batch_op:
        batch_op.drop_column("last_name")

    # ### end Alembic commands ###
