"""empty message

Revision ID: 3d02c50ab4b2
Revises: 
Create Date: 2024-09-17 10:44:56.383229

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d02c50ab4b2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(sa.Column("couriers", sa.ARRAY(sa.String()), nullable=True))
        batch_op.drop_index("ix_order_courier_id")
        batch_op.drop_constraint("order_courier_id_fkey", type_="foreignkey")
        batch_op.drop_column("courier_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("courier_id", sa.UUID(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "order_courier_id_fkey", "courier", ["courier_id"], ["id"]
        )
        batch_op.create_index("ix_order_courier_id", ["courier_id"], unique=False)
        batch_op.drop_column("couriers")

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
