"""empty message

Revision ID: 463fb0c42292
Revises: 36d1c2986a5a
Create Date: 2024-09-23 18:25:14.104966

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "463fb0c42292"
down_revision = "36d1c2986a5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("consumer", schema=None) as batch_op:
        batch_op.alter_column("last_name", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )

    with op.batch_alter_table("consumer", schema=None) as batch_op:
        batch_op.alter_column("last_name", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
