"""empty message

Revision ID: 75867d423034
Revises: f5c530a2ef29
Create Date: 2024-09-07 01:36:54.264505

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75867d423034"
down_revision = "f5c530a2ef29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_constraint("order_consumer_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(None, "consumer", ["consumer_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "order_consumer_id_fkey", "seller", ["consumer_id"], ["id"]
        )

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
