"""empty message

Revision ID: 834bb64da677
Revises: ae7168e1d566
Create Date: 2024-09-07 01:31:24.329771

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "834bb64da677"
down_revision = "ae7168e1d566"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
