"""empty message

Revision ID: 8d0a06f605ca
Revises: 8e7defc18641
Create Date: 2024-09-18 12:06:42.224032

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d0a06f605ca"
down_revision = "8e7defc18641"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(sa.Column("selected_courier", sa.Uuid(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_order_selected_courier"), ["selected_courier"], unique=False
        )
        batch_op.create_foreign_key(None, "courier", ["selected_courier"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_order_selected_courier"))
        batch_op.drop_column("selected_courier")

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
