"""empty message

Revision ID: ae7168e1d566
Revises: 
Create Date: 2024-09-07 01:29:39.054498

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae7168e1d566"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth",
        sa.Column("identity_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_operational", sa.Boolean(), nullable=False),
        sa.Column("roles", sa.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("email"),
        sa.UniqueConstraint("identity_id"),
    )
    op.create_table(
        "courier",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("courier", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_courier_document"), ["document"], unique=True
        )

    op.create_table(
        "seller",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("seller", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_seller_document"), ["document"], unique=True
        )

    op.create_table(
        "item",
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Float(precision=2), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller.id"],
        ),
        sa.PrimaryKeyConstraint("sku", "seller_id"),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_number"), ["number"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_order_seller_id"), ["seller_id"], unique=False
        )

    op.create_table(
        "route",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("courier_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "IN_TRAFFIC",
                "FINALIZED",
                "ABORTED",
                name="status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["courier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("route", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_route_courier_id"), ["courier_id"], unique=False
        )

    op.create_table(
        "order_history",
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("latitude", sa.String(), nullable=False),
        sa.Column("longitude", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["number"],
            ["order.number"],
        ),
        sa.PrimaryKeyConstraint("number", "status"),
    )
    op.create_table(
        "route_order",
        sa.Column("order_number", sa.String(), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_number"],
            ["order.number"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route.id"],
        ),
        sa.PrimaryKeyConstraint("order_number", "route_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("route_order")
    op.drop_table("order_history")
    with op.batch_alter_table("route", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_route_courier_id"))

    op.drop_table("route")
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_seller_id"))
        batch_op.drop_index(batch_op.f("ix_order_number"))

    op.drop_table("order")
    op.drop_table("item")
    with op.batch_alter_table("seller", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seller_document"))

    op.drop_table("seller")
    with op.batch_alter_table("courier", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_courier_document"))

    op.drop_table("courier")
    op.drop_table("auth")
    # ### end Alembic commands ###
