"""empty message

Revision ID: f5c530a2ef29
Revises: 25effa7418ba
Create Date: 2024-09-07 01:36:26.778099

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5c530a2ef29"
down_revision = "25effa7418ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(sa.Column("consumer_id", sa.Uuid(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_order_consumer_id"), ["consumer_id"], unique=False
        )
        batch_op.create_foreign_key(None, "seller", ["consumer_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_order_consumer_id"))
        batch_op.drop_column("consumer_id")

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
