name: Deploy feature

on:
  push:
    branches-ignore:
    - master
    - main
    - dependabot/**
    - temp-*

jobs:
  tests:
      name: Run tests
      runs-on: ubuntu-latest

      steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: make install

      - name: Run tests
        run: make test